export const InitialData  = {
    ProductDetails: {
      productId: "",
      productName: "",
    },
    ThemeType: {
      ThemeSelect: "Minimal",
    },
    CustomizerTitle: {
      CustomizerTitleBackgroundColor: "#ffff",
      CustomizerTitleFontFamily: "",
      CustomizerTitleFontSize: "32px",
      CustomizerTitleFontSizeMobile: "",
      CustomizerTitleFontColor: "#000000",       
      CustomizerTitleFontColorMobile: "#ffff",
      CustomizerTitleDividerColor: "#000000",
      CustomizerTitleDividerThickness: "0px",
    },
    LayersPanel: {
      LayersPanelPosition: "left",
      LayersPanelBackgroundColor: "#ffff",
      LayersPanelBorderColor: "#ffff",
      LayersPanelBorderThickness: "0px",
      LayersPanelErrorColor: "#ffff",
    },
    LayersList: {
      LayersListFontColor: "#000000",
      LayersListFontSize: "",
      LayersListFontFamily: "",
      LayersListDiscriptionFontColor: "#ffff",
      LayersListDiscriptionFontSize: "",
      LayersListDiscriptionFontFamily: "",
      LayersListDividerColor: "#ffff",
      LayersListDividerThickness: "",
    },
    LayersSettings: {
      LayersSettingsBorderColor: "#ffff",
      LayersSettingsSelectedBorderColor: "#ffff",
      LayersSettingsBorderThickness: "",
      LayersSettingsSelectedBorderThickness: "",
      LayersSettingsFontColor: "#ffff",
      LayersSettingsFontSize: "",
      LayersSettingsFontFamily: "",
      LayersSettingsPopUpBackgroundColor: "#ffff",
      LayersSettingsPopUpBackgroundRounding: "",
      LayersSettingsDescriptionFontColor: "#ffff",
      LayersSettingsDescriptionFontSize: "",
      LayersSettingsDescriptionFontFamily: "",
    },
    ThumbnailButton: {
      ThumbnailButtonRoundings: "",
      ThumbnailButtonColoumn: "#ffff",
      ThumbnailButtonWidth: "#ffff",
      ThumbnailButtonHeight: "",
      ThumbnailButtonVerticalMargin: "",
      ThumbnailButtonRoundingMobile: "",
      ThumbnailButtonWidthMobile: "",
      ThumbnailButtonHeightMobile:"",
      ThumbnailButtonMargintMobile:""
    },
    TextInputAndDropdown: {
      TextInputAndDropdownBackgroundColor: "",
      TextInputAndDropdownHeight: "",
      TextInputAndDropdownRounding: "",
      TextInputAndDropdownBorderColor: "",
      TextInputAndDropdownMenuBackgroundColor: "",
      TextInputAndDropdownFontSize: "",
      TextInputAndDropdownHovOpClr: "",
      TextInputAndDropdownFontColor: "",
      TextInputAndDropdownSelcOpClr: "",
      TextInputAndDropdownMenuFontColor: "",
    },
    Customizer: {
      CustomizerLoadingIconColor: "#ffff",
      CustomizerBackgroundColor: "#ffff",
    },
    StepTitle: {
      StepTitleBackgroundColor: "#ffff",
      StepTitleSwitchStepsArrows: "#ffff",
    },
    SummaryTitle: {
      SummaryTitleFontFamily: "",
      SummaryTitleFontColor: "#ffff",
      SummaryTitleFontSize: "",
    },
    AddToCart: {
      AddToCartBorderColor: "#ffff",
      AddToCartBorderThickness: "0px",
      AddToCartBorderRounding: "5px",
      AddToCartFontFamily: "Arial",
      AddToCartFontColor: "#ffff",
      AddToCartBackgroundColor: "#000000",
      AddToCartHoverBackgroundColor: "#ffff",
      AddToCartFontSize: "16px",
    },
    ConfirmButtonMobile: {
      ConfirmButtonMobileFontColor: "#ffff",
      ConfirmButtonMobileBackgroundColor: "#ffff",
    },
    Price: {
      PricePosition: "",
      PriceFontFamily: "",
      PriceFontSize: "",
      PriceFontSizeMobile: "",
      PriceFontColour: "#ffff",
      PriceShowExtraPrice: "",
      PriceExtraPriceFontColor: "#ffff",
      PriceExtraPriceBorderColor: "#ffff",
      PriceExtraPriceBackgroundColor: "#ffff",
    },
    SwitchViewArrows: {
      SwitchViewArrowsColor: "#000000",
    },
    SwitchViewDots: {
      SwitchViewDotsColour: "#737373",
      SwitchViewDotsSelectColour: "grey",
    },
    Zoom: {
      ZoomColor: "#00000",
    },
    ShareButton: {
      ShareButtonDisplayButtonYesNo: "true",
      ShareButtonIconButtonOrTextButton: "false",
      ShareButtonColor: "#00000",
      ShareButtonTextButtonRounding: "",
      ShareButtonTextButtonLength: "small",
    },
    FileUpload: {
      FileUploadBackgroundColor: "#ffff",
      FileUploadBorderColor: "#ffff",
      FileUploadBorderRounding: "",
      FileUploadBorderThickness: "",
      FileUploadFontColor: "#ffff",
      FileUploadLinkColor: "",
      FileUploadFontFamily: "",
      FileUploadFontSize: "",
      FileUploadImgRoundings: "",
      FileUploadRemoveoptionbgColor: "#ffff",
      FileUploadRemoveophoverbgColor: "#ffff",
      FileUploadRemoveIconColor: "#ffff",
    },
     PrintReady: {
          PrintReadyEditionColor: "#ffff",
          PrintReadyEditionIconColor: "#ffff",
          PrintReadyEditionDPIIndicatorTextColor: "#ffff",
          DPILowQualityTextColor: "#ffff",
          LowQualityMessageBackgroundColor: "#ffff",
          LowQualityMessageTextColor:"#ffff",
          DPIHighQualityColor:"#ffff"
        },
    DescriptionMobile: {
      DescriptionMobileColor: "#ffff",
      DescriptionMobileBackgroundColor: "#ffff",
      DescriptionMobileFontFamily: "Arial",
      DescriptionMobileFontSize: "",
    },
    OutOfStock: {
      OutOfStockBadgeIconColor: "#000000",
      OutOfStockBadgeBackgroundColor: "",
      OutOfStockBadgeBorderWidth: "",
      OutOfStockBadgeBorderColor: "#ffff",
      OutOfStockBannerTextColor: "#ffff",
      OutOfStockBannerBackgroundColor: "#ffff",
    },
    };
    export default InitialData;